var tl = new TimelineMax({repeatDelay:0.55, repeat:999});
  tl.add( TweenMax.set('.one,.two,.three,.four',{opacity:0}));
    
    tl 
      .to('.one', 0.04, {opacity:1})    
      .to('.two,.four', 0.10, {opacity:1})    
      .to('.three', 0.02, {opacity:1})          
      .to('.title', 0.1, {skewX:10,ease: Power4.easeInOut})
      .to('.title', 0.04, {opacity:0})
      .to('.title', 0.04, {opacity:1})
      .to('.one', 0.04, {x:-1})                
      .to('.one', 0.04, {x:+1})
      .to('.title-top, .title-bottom', 0.04, { className: '+=redShadow'})
      .to('.title', 0.04, {skewX:0,ease: Power4.easeInOut})
      .to('.three', 0.04, {x:-1})
      .to('.three', 0.04, {x:+1})
      .to('.title', 0.04, {opacity:0})
      .to('.title', 0.04, {opacity:1})
      .to('.title-top, .title-bottom', 0.04, { className: '-=redShadow'})
      .to('.two', 0.04, {x:-1})
      .to('.two', 0.04, {x:+1})
      .to('.three', 0.04, {x:+10})
      .to('.title-top, .title-bottom', 0.03,{ className: '+=greenShadow'})
      .to('.four', 0.04, {x:-1})
      .to('.four', 0.04, {x:+1})
      .to('.three', 0.04, {x:1})
      .to('.title-top, .title-bottom', 0.03,{ className: '-=greenShadow'})